name = "touchgrass-website"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-02-16"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"
