[package]
name = "touchgrass-app"
version = "0.1.0"
description = "touchgrass desktop app"
authors = ["touchgrass"]
license = "LicenseRef-Proprietary"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.10.0", features = [ "devtools"] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-fs = "2"
portable-pty = "0.8"
uuid = { version = "1", features = ["v4"] }
dirs = "6"
libc = "0.2"
