name = "touchgrass-website"
main = "src/index.tsx"
compatibility_date = "2026-02-16"

routes = [
  { pattern = "touchgrass.sh/*", zone_name = "touchgrass.sh" },
  { pattern = "www.touchgrass.sh/*", zone_name = "touchgrass.sh" }
]

[assets]
directory = "./public"
binding = "ASSETS"
